name: esla7
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.1.2
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.4.1
  freezed: ^2.5.2
  get_storage: ^2.1.1
  google_maps_place_picker_mb: ^3.1.2
  image_picker: ^1.1.2
  # localize_and_translate: ^4.1.1
  localize_and_translate: ^6.0.7
  pin_code_text_field: ^1.8.0
  popover: ^0.3.0+1
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: 'assets/icons/android.png'
  image_path_ios: 'assets/icons/ios.png'
  android: true
  ios: true

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/langs/
    - assets/langs/ar.json
    - assets/langs/en.json
    - assets/fonts/

  # fonts
  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: JannaLT-Bold
      fonts:
        - asset: assets/fonts/JannaLT-Bold.ttf
    - family: JannaLT-Regular
      fonts:
        - asset: assets/fonts/JannaLT-Regular.ttf

# name: esla7
# description: A new Flutter application.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# version: 1.0.0+3
# environment:
#   sdk: ">=3.3.4 <4.0.0"
# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   flutter_rating_bar: ^4.0.0
#   carousel_slider: ^4.2.1
#   flutter_staggered_grid_view: ^0.4.1
#   flutter_staggered_animations: ^1.0.0
#   localize_and_translate: ^4.1.1
#   pin_code_text_field: ^1.8.0
#   image_picker: ^1.1.2
#   popover: ^0.2.9
#   google_maps_place_picker: ^2.1.0-nullsafety.3
#   youtube_player_flutter: ^8.1.2
#   firebase_messaging: ^10.0.9
#   flutter_local_notifications: ^8.2.0
#   firebase_core: ^1.24.0
#   flutter_ringtone_player: ^3.2.0
#   flutter_bloc: ^7.0.0
#   bloc: ^7.2.1
#   shared_preferences: ^2.2.3
#   dio: ^4.0.6
#   equatable: ^2.0.3
#   get_storage: ^2.0.3
#   flutter_spinkit: ^5.1.0
#   change_app_package_name: ^1.0.0
#   flutter_launcher_icons: ^0.9.2
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
# flutter_icons:
#   image_path_android: 'assets/icons/android.png'
#   image_path_ios: 'assets/icons/ios.png'
#   android: true
#   ios: true
# flutter:
#   uses-material-design: true
#   # assets
#   assets:
#     - assets/
#     - assets/images/
#     - assets/icons/
#     - assets/langs/
#     - assets/langs/ar.json
#     - assets/langs/en-gb.json
#     - assets/fonts/
#   # fonts
#   fonts:
#     - family: Roboto-Bold
#       fonts:
#         - asset: assets/fonts/Roboto-Bold.ttf
#     - family: Roboto-Regular
#       fonts:
#         - asset: assets/fonts/Roboto-Regular.ttf
#     - family: JannaLT-Bold
#       fonts:
#         - asset: assets/fonts/JannaLT-Bold.ttf
#     - family: JannaLT-Regular
#       fonts:
#         - asset: assets/fonts/JannaLT-Regular.ttf
